// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWEiZ2oVVMvD61gfMKAf_crCCcxlG-ghI',
    appId: '1:503327814229:web:c431f51a6a081593025adc',
    messagingSenderId: '503327814229',
    projectId: 'uzone-3e5ce',
    authDomain: 'uzone-3e5ce.firebaseapp.com',
    storageBucket: 'uzone-3e5ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZlL3D6_zftn7aWADwBC5aYAaJMi_lX24',
    appId: '1:503327814229:android:aa8e13f5ad4df3bd025adc',
    messagingSenderId: '503327814229',
    projectId: 'uzone-3e5ce',
    storageBucket: 'uzone-3e5ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgtA9oWzCj-o-J6_su0UI1Bujivp0GSp4',
    appId: '1:503327814229:ios:2cbe5681ef2d5f4d025adc',
    messagingSenderId: '503327814229',
    projectId: 'uzone-3e5ce',
    storageBucket: 'uzone-3e5ce.appspot.com',
    iosBundleId: 'com.example.uzone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgtA9oWzCj-o-J6_su0UI1Bujivp0GSp4',
    appId: '1:503327814229:ios:45019c7220085789025adc',
    messagingSenderId: '503327814229',
    projectId: 'uzone-3e5ce',
    storageBucket: 'uzone-3e5ce.appspot.com',
    iosBundleId: 'com.example.uzone.RunnerTests',
  );
}
